project:
  type: website

website:
  title: "Wyatt Stone"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Work Experience
      - href: Projects.qmd
        text: Academic Experience

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto
 


